### ISSUE TITLE
Project not building, tutorial steps no accurate

### ISSUE THREAD

**Issue by shinshichirou** [rileytestut/Delta#121]
If you use tutorial in readme step by step than project isn't building.

Two errors appear:

1) 
..../Delta/Cores/N64DeltaCore/Mupen64Plus/GLideN64/src/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp:12:10: 'Revision.h' file not found

2)
No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "6XVY5G3U44" with a private key was found. (in target 'Systems' from project 'Systems')

How can this be solved? Thanks in advance :)

P.S. Using Xcode 12.5 (12E262), iPhone 12 mini (12.5)

**Comment by lukecarbis** [comment]
Same problem for me.

**Comment by lukecarbis** [comment]
This fixed the `Revision.h` problem for me: https://github.com/rileytestut/Delta/issues/59#issuecomment-619577505

**Comment by lukecarbis** [comment]
I just fixed the second problem by opening `Systems/Systems.xcodeproj`, and choosing the correct Team under Targets > Signing Capabilities.

**Comment by shinshichirou** [comment]
Thank's, i guess this info should be added in readme.

**Comment by thiagocorreiap** [comment]
> If you use tutorial in readme step by step than project isn't building.
> 
> Two errors appear:
> 
> 
> ..../Delta/Cores/N64DeltaCore/Mupen64Plus/GLideN64/src/Graphics/OpenGLContext/mupen64plus/mupen64plus_DisplayWindow.cpp:12:10: 'Revision.h' file not found
> 
> 
> No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "6XVY5G3U44" with a private key was found. (in target 'Systems' from project 'Systems')
> 
> How can this be solved? Thanks in advance :)
> 
> P.S. Using Xcode 12.5 (12E262), iPhone 12 mini (12.5)

I was having both same issues! While digging through the files I discovered @lukecarbis solution for the 'Revision.h' and was able to fix my issue.

**Comment by thiagocorreiap** [comment]
> I just fixed the second problem by opening `Systems/Systems.xcodeproj`, and choosing the correct Team under Targets > Signing Capabilities.

Wow, thank you! I almost gave up because I couldn't fix this problem. Now everything worked for me.

**Comment by lbibass** [comment]
I am still having issues with compiling this. I've followed all the steps, but I keep getting this error. 

```Module 'Systems' was created for incompatible target arm64-apple-ios12.0```
